language: generic
#for uusing docker
sudo: required
services:
  - docker

before_install:
  - docker build -t pm/workflow-example -f Dockerfile.dev .

script:
  - docker run -e CI=true pm/workflow-example npm run test